services:
  jellyfin-filename-as-title:
    container_name: jellyfin-filename-as-title
    image: ghcr.io/flandredaisuki/jellyfin-filename-as-title
    restart: unless-stopped
    environment:
      - USER_NAME=${USER_NAME}
      - API_TOKEN=${API_TOKEN}
      - BASE_URI=${BASE_URI}
